name = "dev"
main = "worker.js"
compatibility_date = "2023-07-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_id = ""
preview_database_id = ""

[assets]
binding = "ASSETS"
directory = "./public"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
JWT_SECRET = "your-secret-key-here-please-change-in-production"
 